emmedy_h5p.ajax:
  resource: "@EmmedyH5PBundle/Controller/H5PAJAXController.php"
  type:     annotation

emmedy_h5p.interaction:
  resource: "@EmmedyH5PBundle/Controller/H5PInteractionController.php"
  type:     annotation
