studit_h5p.ajax:
  resource: "@StuditH5PBundle/Controller/H5PAJAXController.php"
  type:     attribute

studit_h5p.interaction:
  resource: "@StuditH5PBundle/Controller/H5PInteractionController.php"
  type:     attribute
