<?php

namespace Emmedy\H5PBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LibraryLibrariesRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class LibraryLibrariesRepository extends EntityRepository
{
    public function countLibraries($libraryId)
    {
        $qb = $this->createQueryBuilder('l')
            ->select('COUNT(l)')
            ->where('l.libraryId = :id')
            ->setParameter('id', $libraryId);

        return $qb->getQuery()->getSingleScalarResult();
    }
}
