name: "CI Tests"

on: [push, pull_request]

jobs:
  test:
    runs-on: 'ubuntu-20.04'
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3']
        symfony: ['6.0.*', '6.1.*', '6.2.*', '6.3.*', '6.4.*', '7.0.*', '7.1.*']
        composer-flags: ['--prefer-stable']
        extensions: ['curl, iconv, mbstring, pdo, pdo_sqlite, sqlite, zip']
        include:
          - php: '8.1'
            symfony: '6.0.*'
            composer-flags: '--prefer-stable --prefer-lowest'
            extensions: 'curl, iconv, mbstring, pdo, pdo_sqlite, sqlite, zip'
        exclude:
          - php: '8.1'
            symfony: '7.0.*'
          - php: '8.1'
            symfony: '7.1.*'
          - php: '8.2'
            symfony: '6.0.*'
    name: "PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }}${{ matrix.composer-flags != '' && format(' - Composer {0}', matrix.composer-flags) || '' }}"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-symfony-${{ matrix.symfony }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}-flags-${{ matrix.composer-flags }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, flex
          extensions: ${{ matrix.extensions }}
          coverage: none
      - name: Install dependencies
        run: composer update ${{ matrix.composer-flags }} --prefer-dist --no-suggest
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}

      - name: Run PHPUnit
        run: bin/phpunit --verbose
 