name: "CI Tests"

on: [push, pull_request]
jobs:
  build-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
      - uses: php-actions/phpstan@v3
        with:
          memory_limit: -1